import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { Providers } from "./providers";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "AI Product Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        <Providers>
          <Suspense>
            <Navbar />
          </Suspense>
          <main className="mx-auto max-w-7xl px-4 py-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
