version: "3.8"
services:
  pg:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ai_search
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
